version: "3"
services: 
    redis:
      image: redis:latest

    postgres:
      image: postgres
      env_file: 
        - database.env
      volumes: 
        - ./home :/var/lib/postgres
    app:
      build: ./
      links: 
        - redis
      volumes: 
        - ./:/var/www/app
      ports:
        - "4000:4000"
      environment: 
        - REDIS_URL=redis://redis:6379
        - PORT=8080
      command: 
        sh -c 'npm i && node index.js'
